### ISSUE TITLE
execute [FBSDKShareDialog showFromViewController: withContent: delegate:self] the step too much time

### ISSUE THREAD

**Issue by Pcookie** [facebook/facebook-ios-sdk#1053]
## Checklist
 I've updated to the latest released version of the SDK
 I've searched for existing [GitHub issues](https://github.com/facebook/facebook-objc-sdk/issues)
  I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `11.0`
- SDK Version : 5.6.0

I update SDK Version to 5.6.0 from 4xx, I find share function can't response，I check my code，
[FBSDKShareDialog showFromViewController: withContent: delegate:self] the step too much time，about spend 7 second, only then the share box appear.

**Comment by kdantley** [comment]
#1049 ###

**Comment by Pcookie** [comment]
> ## Checklist
> I've updated to the latest released version of the SDK
> I've searched for existing [GitHub issues](https://github.com/facebook/facebook-objc-sdk/issues)
> I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
> 
> ## Environment
> Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:
> 
> * Xcode Version: `11.0`
> * SDK Version : 6.5.0
> 
> I update SDK Version to 6.5.0 from 4xx, I find share function can't response，I check my code，
> [FBSDKShareDialog showFromViewController: withContent: delegate:self] the step too much time，about spend 7 second, only then the share box appear.

RunMode:FBSDKShareDialogModeBrowser

**Comment by tianqibt** [comment]
@Pcookie our latest SDK version is 5.6.0. We are not able to reproduce this problem with our test app. Would you please provide a test app so we can reproduce it?

**Comment by kross51** [comment]
Same here... animation takes too long and is not smooth showing screen as blank for a 1/2 second before presentation animation completes:

On all of my test bench iPhones (11 Pro Max/Pro/11/XS/etc)
iOS 13.1.1
Xcode 11 (seed 2)
FB iOS SDK: 5.7.0

Executing the following on the main thread:

FBSDKSharePhoto *photo = [FBSDKSharePhoto photoWithImage:image userGenerated:YES];
FBSDKShareVideo *video = [FBSDKShareVideo videoWithVideoURL:assetURL previewPhoto:photo];
                            
FBSDKShareVideoContent *content = [[FBSDKShareVideoContent alloc] init];
content.video = video;
content.hashtag = [FBSDKHashtag hashtagWithString:@“#ABC”];
[FBSDKShareDialog showFromViewController:weakSelf withContent:content delegate:self];

**Comment by Pcookie** [comment]
> @Pcookie our latest SDK version is 5.6.0. We are not able to reproduce this problem with our test app. Would you please provide a test app so we can reproduce it?

oh,sorry  ，i can't provide a test app...but you can see that @kross51 , He has the same problem

**Comment by kross51** [comment]
Is someone going to look into this reported issue???

**Comment by kross51** [comment]
Again, is anyone going to look into this or is this going to sit in limbo forever???

**Comment by tianqibt** [comment]
@kross51 we have forwarded to related team, but have not heard of anything yet. @joesus do you have bandwidth to take a look? Thanks!

**Comment by joesus** [comment]
@Pcookie it looks like the run mode you've specified is `FBSDKShareDialogModeBrowser`. This only supports sharing links... what specifically are you trying to share? It would help to know to diagnose the issue.

**Comment by joesus** [comment]
@Pcookie, @kross51
Are you able to provide any type of video (timestamps help!) to give us a better sense of what the root cause might be? This type of sharing occurs in the facebook app so any type of slowdown related to a specific FB App release might also result in a lag while it launches.

But without a test app or video this will be near impossible to debug. Thanks!

**Comment by kross51** [comment]
It looks like there is a non-transparent background immediately displayed right before the animated slidein (from bottom-to-top) of the sharesheet.  Then as the rounded edge sharesheet/view slides in, there seems to be a non-transparent view animating in right behind it.  So that all gives the appears of the screen blanking out right before and during the animating in of the sharesheet.  Anything behind the rounded edge share sheet should be transparent to not obscure the view it is being animated over.  This used to be the previous behavior but something changed.  Maybe something either changed in newer FB code or something in iOS 13 with views and layers that FB needs to now account for.  At any rate, those layers need to be made transparent.

**Comment by joesus** [comment]
Closing because there is no video, sample app, or other means of debugging. Please post a reproducible sample if this is still occurring. Thanks!

**Comment by kamalalnabrissi2017** [comment]
Dear
Plz shall u give me some hints about facebook sdk ios platforms
