### ISSUE TITLE
facebook login:FBSDKLoginManagerLoginResult result.isCancelled

### ISSUE THREAD

**Issue by weisx** [facebook/facebook-ios-sdk#1188]
I used a custom button to log in. It has always been normal. Recently, a large number of users in the application have returned to FBSDKLoginManagerLoginResult * result after calling facebook login.
result.isCancelled; I didn't make any changes, why? Is it because the license has expired?

**Comment by weisx** [comment]
I use version 4.39.0

**Comment by joesus** [comment]
Hi! 
Is it possible to update to a more recent version of the SDK? It is highly possible that the error has been corrected in a later version. 

Also, it's hard to say without more information but this sounds like it could have to do with use of `SceneDelegate` with iOS 13. There were some changes made to how deep links work which could be related to what you're seeing. 

As far as your question about licensure goes. I'm not sure what license you are referring to. 

Closing for now because there is not enough information to provide any help. Please try upgrading the version or providing more details and if you're still having issues we can reopen this issue and help you address them. Thanks!

**Comment by weisx** [comment]
OK, I will try to upgrade the version.
