### ISSUE TITLE
NSLocationWhenInUseUsageDescription required by Apple because CoreLocation is used in Facebook SDKs

### ISSUE THREAD

**Issue by ggdiez** [facebook/facebook-ios-sdk#1266]
## Environment

- Xcode Version: `11.3.1`
- Swift Version: `5` 
- Installation Platform & Version: `Cocoapods` version `6.0.0`

## Goals

Submit new release of the app to the App Store

## Expected Results

Not receive an App Store warning mail each time to upload the app version

## Actual Results

Each time that I send a version to App Store I receive a warning email:

We identified one or more issues with a recent delivery for your app, "XXXXX" 2.6 (9). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

I'm not use location request in my app. Looking for CoreLocation use I can see in the pods that is using by Facebook sdk. I attached a screenshot.

## Steps to Reproduce

Upload new app versión from Xcode.

![Core Location](https://user-images.githubusercontent.com/2051473/75542893-f8edaa80-5a20-11ea-8209-6b03c228c073.png)

**Comment by joesus** [comment]
You are correct that the libraries are weak-linking the CoreLocation framework. What is unclear is why since they do not appear to use them in any capacity.

Opening a PR to remove these from the Cocoapods. In the meantime you may want to try using Swift Package Manager since the libraries produced that way do not link CoreLocation.

I would check with Apple again and also double check to see if any of the other libraries you are using  (or your own code?) make any references to the CoreLocation framework.

Closing for now. Will reopen if there is more evidence that the rejection was a direct result of including the Facebook SDK.

**Comment by ggdiez** [comment]
Thanks for the quick PR and Merge. I updated my project to point to master branch and CoreLocation reference does not exist. Finally I have published new version of my app without problems.

**Comment by joesus** [comment]
Glad to hear it!
