### ISSUE TITLE
FBSDKShareKit needs to be split to exclude APIs those require NSPhotoLibraryUsageDescription

### ISSUE THREAD

**Issue by CharlieReece** [facebook/facebook-ios-sdk#1357]
FBSDKShareKit  requires "NSPhotoLibraryUsageDescription" even if we do not use it for video or photo. I do not just want to add that line to my plist because of an unused feature of a 3rd party library. ShareKit needs to be split.

**Comment by joesus** [comment]
Out of curiosity, if you do not wind up using photo or video sharing features, what is the downside of adding a NSPhotoLibraryUsageDescription to the plist? It would only ever be shown if you tried to access the photo library right?

**Comment by CharlieReece** [comment]
To add that key, I must type a "lie" into the value of "NSPhotoLibraryUsageDescription" about how my app is "currently" using that permission. For example, If I type "This app needs your permission to access your photos to share them on Facebook". No, that is a lie, my app does not do that. If I type "You need to give permission so we can access your photo library.", what would that mean? Why? When? For what? Advertising directly or indirectly something that is not actually supported by my app. "Technically", yes, that would possibly not create any problems, but it doesn't feel right. If so, everyone could just add all of those permissions into info.plist even if they don't use any of them. So, the default project could come with all of those permissions in info.plist and in that case why would Apple bother, they could just remove those requirements from info.plist? Do you see the point? I can manually remove all unnecessary codes from FBSDKShareKit that is triggering Apple's API check on App Store submission but that will take my time and I won't be able to update to the next version or patched versions easily when they become available. I could not even find anything related to this "NSPhotoLibraryUsageDescription" requirement in FB SDK documents (it may exist but it is probably well hidden somewhere). I do not know why people are not complaning. They just copy and paste solutions around internet without even judging. I think this is necessary. At least something like FBSDKShareBasicKit, FBSDKShareCoreKit or something like that could include everything that does not trigger Apple's API check and FBSDKShareKit could depend on that kit with additional code that supports Image and Video related codes.

**Comment by joesus** [comment]
You make some interesting points. A few questions:

> FBSDKShareKit requires "NSPhotoLibraryUsageDescription" even if we do not use it for video or photo.

I'm assuming this came up during Apple's app review process. Is this correct? Reason I'm asking is that this description is not needed for ShareKit to work if you are not accessing the photo library. For example [FacebookShareSample](https://github.com/facebook/facebook-ios-sdk/tree/master/samples/FacebookShareSample) shows how to share a link and does not require `NSPhotoLibraryUsageDescription` to operate.

> At least something like FBSDKShareBasicKit
This is not a bad idea and would welcome an open  source contribution. I'm hesitant to invest time into this because it may wind up being a decent amount of work to prevent having to add a single boilerplate line. That said if it is indeed required for app store submission then I can ask that we emphasize that in the documentation on the dev site.

> If I type "This app needs your permission to access your photos to share them on Facebook". No, that is a lie, my app does not do that. If I type "You need to give permission so we can access your photo library.", what would that mean?

I think this is irrelevant if you are never requesting permission. What were you envisioning would be included in a ShareKitBasics library?

**Comment by joesus** [comment]
Closing but please feel welcome to contribute if there's a feature you'd like to see.
