### ISSUE TITLE
can support mac_catalyst? please.

### ISSUE THREAD

**Issue by Lionwey** [facebook/facebook-ios-sdk#1381]
## Checklist

- [ ] I've updated to the latest released version of the SDK
- [ ] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [ ] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [ ] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

What do you want to achieve?

## Expected Results

What do you expect to happen?

## Code Samples & Details

Please provide a code sample, as well as any additional details, to help us track down the issue. If you can provide a link to a test project that allows us to reproduce the issue, this helps us immensely in both the speed and quality of the fix.

**Note:** Remember to format your code for readability:

```swift
// INSERT YOUR CODE HERE

var example = "Example code"
```

**Comment by joesus** [comment]
We support mac catalyst but do not distribute the binaries at this time. Reason being that our CI pipeline uses Travis CI which does not support Catalina as of yet. The may change at some point -- Travis will upgrade or we will find an alternative build solution -- but in the meantime you are welcome to clone the repository and build for mac catalyst in Xcode. Closing the issue since this is a known issue and on our radar. Thanks!

**Comment by roarapps** [comment]
TravisCI now supports catalina. Catalyst build plzzz :)
