### ISSUE TITLE
pod FBSDKCoreKit/Swift, pod 'FBSDKCoreKit/Swift' update

### ISSUE THREAD

**Issue by NikKovIos** [facebook/facebook-ios-sdk#1386]
Cocoapods now install 6.5.2 version of FBSDKCoreKit/Swift and FBSDKLoginKit/Swift. What about updating them to 7.0.0?

**Comment by joesus** [comment]
These pods are no longer necessary. v7.0 of the regular pods are now equivalent. Cheers!

**Comment by NikKovIos** [comment]
@joesus in https://github.com/facebookarchive/facebook-swift-sdk it tells, that we need use `pod FBSDKCoreKit/Swift` what do you mean with your answer above?

**Comment by joesus** [comment]
@NikKovIos sorry. The most recent version, 7.0.0 removes the separation between regular and swift specific targets. If you were using “pod FBSDKCoreKit/Swift” you should now use “pod FBSDKCoreKit”. You will still have access to swift interfaces.

**Comment by Paul-van-Klaveren** [comment]
@joesus Please have someone update the instructions on [Facebook Analytics Quickstart Guide for iOS](https://developers.facebook.com/docs/analytics/quickstart-list/ios?sdk=cocoapods#).
It still reads: `pod 'FBSDKCoreKit/Swift'`

**Comment by 123gid** [comment]
Can you do it for me please Sent from Mail for Windows 10 From: Paul van KlaverenSent: Monday, April 19, 2021 5:47 PMTo: facebook/facebook-ios-sdkCc: SubscribedSubject: Re: [facebook/facebook-ios-sdk] pod FBSDKCoreKit/Swift, pod 'FBSDKCoreKit/Swift' update ***@***.*** Please have someone update the instructions on Facebook Analytics Quickstart Guide for iOS.It still reads: pod 'FBSDKCoreKit/Swift'—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by joesus** [comment]
Done! Thanks for the feedback @Paul-van-Klaveren!

**Comment by 123gid** [comment]
Yes sir, you mean now the sDKs is resolved Sent from Mail for Windows 10 From: Joe SusnickSent: Wednesday, April 21, 2021 2:13 AMTo: facebook/facebook-ios-sdkCc: 123gid; CommentSubject: Re: [facebook/facebook-ios-sdk] pod FBSDKCoreKit/Swift, pod 'FBSDKCoreKit/Swift' update (#1386) Done! Thanks for the feedback @Paul-van-Klaveren!—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by 123gid** [comment]
I also would like to check for me what remaining to be added to be functional in google play store please. Sent from Mail for Windows 10 From: Joe SusnickSent: Wednesday, April 21, 2021 2:13 AMTo: facebook/facebook-ios-sdkCc: 123gid; CommentSubject: Re: [facebook/facebook-ios-sdk] pod FBSDKCoreKit/Swift, pod 'FBSDKCoreKit/Swift' update (#1386) Done! Thanks for the feedback @Paul-van-Klaveren!—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
