### ISSUE TITLE
Allow developers to implement Facebook Login without the official SDK

### ISSUE THREAD

**Issue by Jumhyn** [facebook/facebook-ios-sdk#1437]
The current [Facebook Developer Policy](https://developers.facebook.com/policy/) requires that developers use the official Facebook SDK when implementing Facebook Login in their native app. Given that Facebook cannot ensure the stability of their SDK (resulting in the crashing of client apps), developers should have a policy-compliant option for implementing the login API themselves to avoid Facebook's QA practices rendering their apps unusable.

Section 8.2 of the above-linked page:

> - Native iOS and Android apps that implement Facebook Login must use our official SDKs for login.

**Comment by vishalnandagopal** [comment]
Why would they, when it would reduce the tracking they could do in a 3rd party app? This is Facebook. Let's be realistic

**Comment by ethanhuang13** [comment]
If you need sample code of this, see my [gist](https://gist.github.com/ethanhuang13/70c27ea9b5eb53199bc67c3bc9d47b7b) with just ~100 loc.

**Comment by LeoNatan** [comment]
People should just not use Facebook SDK and remove Facebook Login. It’s that simple. Any developer still using the SDK is complicit in this behavior and should be given a one star review on App Store whenever their silly app crashes because of the SDK.

**Comment by mojidabckuu** [comment]
The AppLaunch Xcode template shows 120ms consumption on FacebookSDK! That's a good point to write custom login and do not execute thousands lines of code for that simple action.

**Comment by Legoless** [comment]
There is also another reason for this. We're a kids category app and we've had Facebook login for years. But recently we've been stuck in review for weeks, because of code references to IDFA and Facebook collecting anonymous ID's (which shouldn't be a problem, but apparently Apple doesn't like Facebook very much).

**Comment by chrasuf** [comment]
It appear to be resolved, isn't it? Link above does not mention the native application now. Other page for Dev Policy, the section Login (https://developers.facebook.com/devpolicy/#login) say:

> 2. If your app uses a manual Facebook Login flow (i.e. if your app is not using our SDKs to enable Facebook Login), check the validity of the session every 24 hours and log users out if it is no longer valid. Our SDKs perform this check automatically.

I am not Facebook, only developer working to make login. Can Facebook say anything?

**Comment by Legoless** [comment]
Or at least provide sample code to implement this without SDK? Thanks.

**Comment by jawwad** [comment]
Since the policy has now been amended I'm going to close this issue out.

@Legoless - See https://github.com/facebook/facebook-ios-sdk/issues/1437#issuecomment-656777740 in which @ethanhuang13 linked a gist with some sample code.

There is also some information here on how to use the GraphAPI calls directly:
https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/

**Comment by Legoless** [comment]
@jawwad Well, yeah, we also maintain our own version. But really, we were trying to avoid custom implementations, since SDK already provides this functionality (for example all FB Login requirements, such as checking validity of the session every 24 hours). I'm not seeing the reason why SDK cannot implement a conditional compilation for IDFA code, same as many others have done?

**Comment by jawwad** [comment]
@Legoless - So this issue is about allowing developers to implement Facebook Login without the official SDK. The previous policy was that developers needed to use the official Facebook SDK to implement Login but that is no longer a requirement.

**Comment by Legoless** [comment]
Oh, thanks for clearing that up, I actually thought I was replying to another issue.

**Comment by jawwad** [comment]
> Oh, thanks for clearing that up, I actually thought I was replying to another issue.

Aah got it. I think your comment was meant for #1475.

**Comment by Legoless** [comment]
You, sir, are correct. :D
