### ISSUE TITLE
Multiple "Double-quoted include" warnings

### ISSUE THREAD

**Issue by vladogrigorov** [facebook/facebook-ios-sdk#1504]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: 12.0
- Swift Version: 5 (if issue is Swift related)
- Installation Platform & Verison: `[Manual]` version `8.0.0`

## Goals

Build my app without warnings.

## Actual Results

When I build my app with Facebook SDK 8.0.0 many warnings appear:

`FBSDKCoreKit.framework/Headers/FBSDKCoreKit.h:65:10: warning: double-quoted include "FBSDKAccessToken.h" in framework header, expected angle-bracketed instead [-Wquoted-include-in-framework-header]
 #import "FBSDKAccessToken.h"`

**Comment by arthur-tam** [comment]
I have the same issue and that happen even include facebook sdk 8.0.0

**Comment by joesus** [comment]
Are you able to link a simple sample app that shows this? There are many ways to include the SDK in a project and it's very hard to replicate issues without knowing precisely how a project and the SDK are integrated.

**Comment by jawwad** [comment]
It looks like this is due to a new warning in Xcode 12: `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER`. Under build settings this warning shows up under the "Quoted Include in Framework Header" settings. 

You can either turn off that warning for your Xcode project or you can add the `-Wno-quoted-include-in-framework-header` compiler flag to the files that are causing the warning in the Compile Sources section under Build Phases. (Select all files you want to add the flag to, double click on any one file and then paste in the `-Wno-quoted-include-in-framework-header` flag and it should get applied to all files).

**Comment by jawwad** [comment]
Closing this out since I don't think we have these warnings enabled.
