### ISSUE TITLE
Feature Request: Distribute static framework via Carthage

### ISSUE THREAD

**Issue by Wisors** [facebook/facebook-ios-sdk#1540]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

I'm trying to update our project to the latest SDK(8.0.0) and can't do it because Carthage installs dynamic build with a specific compiler version that doesn't match mine.

## Expected Results

Having a static framework with library evolution and module stability options turned on (`BUILD_LIBRARY_FOR_DISTRIBUTION`) distributed via Carthage.

## Code Samples & Details

Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler: /Users/1/IOS-24891/ThirdParty/Carthage/Build/iOS/FBSDKCoreKit.framework/Modules/FBSDKCoreKit.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

**Comment by joesus** [comment]
This is impossible right now since we need to use either Xcode 11.x or 12.x to build the static libraries that are uploaded to the release. 

I think there's a valuable conversation to be had regarding which Xcode version is the default for this but for now it's 11.x. I believe carthage has a caching option in case you need to build the frameworks locally using carthage and want to save time. You can find information on this at https://github.com/Carthage/Carthage#caching-builds

**Comment by psolt-gpsw** [comment]
Hopefully you can fix this in the near future. The lack of Module Stability makes the prebuilt option not work if you are manually pulling in the library.

I rebuilt library with Module Stability enabled using Carthage.
