### ISSUE TITLE
fetchDeferredAppLink receives nil

### ISSUE THREAD

**Issue by andreiYarash** [facebook/facebook-ios-sdk#1562]
In closure of the fetchDeferredAppLink method I receive url-nil! if started after update on iOS 14 and new sdk version. on iOS 13 worked fine! Please tell me what is wrong! I am testing view Facebook tool for deferred deep links!
Thanks

**Comment by andreiYarash** [comment]
code of the method https://ibb.co/T4xY4vH

**Comment by TimPapler** [comment]
yes, we are having same issue, when getting a deferred link from facebook ads. Please advise.

**Comment by madhikarma** [comment]
Hi there

We've also been experiencing issue with `fetchDeferredAppLink` returning a `nil` `URL`.

- We noticed a drop off from a backend API endpoint of ours that receives data after this call. 
- It was in between iOS releases in early December (around midnight) 
- App analytics show the URL to be nil but no `Error` object either 
- We have tried upgrading our Facebook iOS SDK versions in our app to the latest versions at the time (twice) but no improvement yet (we are using SwiftPM)
- We have also been looking at our ad setup to see why the URLs are now nil but they all look to be configured correctly.

Currently we're blocked from delivering a feature to users and also an existing feature no longer works because of this.

Is there any plan for Facebook's iOS SDK team to investigate this issue? 

If there is any further info or help we can do to help you debug this let us know 

Thank you

**Comment by joesus** [comment]
I remember there was a change where deep linking won't work on devices where the limit ad tracking setting is enabled. Could this be the case here?

**Comment by TimPapler** [comment]
Yea, that could be it. 👍

**Comment by victor-yn** [comment]
Hello there, is there any news on this topic? This issue is still happening, both `url` and `error` are `nil` even after the IDFA permission being turned on.

`fetchDeferredAppLink` is dead w/ the IDFA policy?

**Comment by victor-yn** [comment]
Hello there @joesus , is there any news on this topic? This issue is still happening, both `url` and `error` are `nil` even after the IDFA permission being turned on. 

`fetchDeferredAppLink` is dead w/ the IDFA policy?

**Comment by KylinChang** [comment]
Hi @victor-yn , it only works when IDFA is not nil and additionally you need to set ATE(AdvertiserTrackingEnabled) to be true to have it work in iOS 14+

**Comment by victor-yn** [comment]
Hello @KylinChang , I confirm IDFA is not nil and ATE(AdvertiserTrackingEnabled) is set to true.

Here's a code snippet:

```swift
ATTrackingManager.requestTrackingAuthorization { status in
    switch status {
    case .authorized:
        Settings.setAdvertiserTrackingEnabled(true)
        AppLinkUtility.fetchDeferredAppLink { url, error in
            /* At that point, both url and error are nil */
        }
    default: break
    }
}
```

Both `url` and `error` are `nil` here

**Comment by DSPerson** [comment]
I found out why. You must turn on You's and facebook's app Advertiser tracking!!!!

**Comment by hapiii** [comment]
> I found out why. You must turn on You's and facebook's app Advertiser tracking!!!!

How to actively trigger the facebook ATT popup? I can't find a place to turn on facebook AD tracking

**Comment by sulizhan** [comment]
> > I found out why. You must turn on You's and facebook's app Advertiser tracking!!!!
> 
> How to actively trigger the facebook ATT popup? I can't find a place to turn on facebook AD tracking

reopen Facebook application few times,  will request ATT permission.  but still not work for me. url and error alway nil.   disappointing.
