### ISSUE TITLE
FBAudienceNetwork has a build warning: 'FBInstreamAdView' is deprecated

### ISSUE THREAD

**Issue by tinder-owenthomas** [facebook/facebook-ios-sdk#1565]
##  Environment
Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `12.1.0`
- Swift Version: `4.2.0` (if issue is Swift related)
- Installation Platform & Verison: `Cocoapods` version `1.10.0`

## Goals
Building without warnings

## Expected Results
Building without warnings

## Actual Results
There is a build warning inside the framework itself: `'FBInstreamAdView' is deprecated: Instream ads have been deprecated.` 

It appears that `FBInstreamAdView` has been deprecated in the very same file in which it is still used, causing an internal build warning within FBAudienceNetwork. Since our CI process will not pass with any warnings in the project, we simply cannot update FBAudienceNetwork anymore.

## Steps to Reproduce
Add FBAudienceNetwork to a project and build

**Comment by jawwad** [comment]
Hi @tinder-owenthomas,

I checked in our source and looks like the FBInstreamAdView classes were recently removed so this should be fixed with the next release of the FBAudienceNetwork SDK. In the meantime I believe you can ignore warnings from a specific Pod by using the `inhibit_warnings => true` option for example:

```ruby
pod 'FBAudienceNetwork', :inhibit_warnings => true
```

Let me know if that works for you.

**Comment by tinder-owenthomas** [comment]
Thank you, that is great news @jawwad. Do you know if there is a regular release cadence for the FBAudienceNetwork SDK? Just curious when the next release is likely to be.

**Comment by jawwad** [comment]
Hi @tinder-owenthomas - There isn't a scheduled release cadence so not sure when the next release will be. Just depends on when the Audience Network team decides to do a release. However, judging from the CocoaPods specs it looks like it is released every 1 or 2 months:

https://github.com/CocoaPods/Specs/commits/master/Specs/2/1/5/FBAudienceNetwork

It also looks like releases are slower during this time of the year due to the holiday slowdown and code freezes since there was there was a 3 month period between the 10/28/2019 and the 01/28/2020 release.

**Comment by tinder-owenthomas** [comment]
Thanks for pointing that out. I wasn't able to find the spec history you linked to when I searched. I'll look out for a release in the new year!

Thanks again :)

**Comment by Tayphoon** [comment]
We still se this warning FBAudienceNetwork 6.2.0

**Comment by tinder-owenthomas** [comment]
Me too. Hoping it can be resolved in 6.3.0 @jawwad?

**Comment by tinder-owenthomas** [comment]
@jawwad Can this be reopened, please? The issue is still impacting version 6.2.1.
