### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FBLoginButton

### ISSUE THREAD

**Issue by tr1et** [facebook/facebook-ios-sdk#1595]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [x] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `12.2 (12B45b)` and `11.7 (11E801a)`
- Swift Version: `5`
- Installation Platform & Version: `Cocoapods` version `1.10.0`

## Goals

Use view `FBLoginButton` to add Facebook login button to a tvOS app (according to [the Facebook login documentation](https://developers.facebook.com/docs/facebook-login/ios/)) or use class `FBSDKLoginManager` to do the login manually (according to [the Facebook login advanced documentation](https://developers.facebook.com/docs/facebook-login/ios/advanced#review))

## Expected Results

The compiler can both compile the app using the `FBLoginButton` and the editor can find the class `FBSDKLoginManager`

## Actual Results

- The compiler can not compile the class `FBLoginButton` (found in editor but can not compile)

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FBLoginButton", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

- XCode can not find the class `FBSDKLoginManager`

![Screen Shot 2020-12-12 at 8 24 29 PM](https://user-images.githubusercontent.com/13586514/101985078-396c9b00-3cb8-11eb-935f-3f8294600e15.png)

## Steps to Reproduce

- Init a empty Swift, UIKit, Storyboard project from XCode.
- Run `pod init` in the root project folder, same level as `projectname.xcodeproj`
- Edit the `Podfile` file as follow and `pod install`:

```Podfile
platform :tvos, '12.0'

target 'projectname' do
  use_frameworks!

  pod 'FBSDKCoreKit', '~> 8.2.0'
  pod 'FBSDKLoginKit', '~> 8.2.0'

end
```

- Edit the `projectname/ViewController.swift` and as follow:

```Swift
import UIKit

import FBSDKCoreKit
import FBSDKLoginKit

class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let view = FBLoginButton()
//        let manager = FBSDKLoginManager()
    }
}
```

- Build the project and the compiler throw error `Undefined symbol: _OBJC_CLASS_$_FBLoginButton`
- Uncomment the `FBSDKLoginManager` line and the editor show error `Cannot find 'FBSDKLoginManager' in scope`

### Additional details

- Tried versions:  `7.0.1`, `7.1.1`, `8.0.0` and `8.2.0` (latest as of 2020/12/12)
- Tried XCode 12 and 11.7
- Tested and had the same errors on 2 projects: 1 blank project and 1 packed project.
  - The packed project has Facebook app registered, completed all the items in the 2 documentations ([Getting Started](https://developers.facebook.com/docs/ios/getting-started/) and [Facebook login](https://developers.facebook.com/docs/facebook-login/ios))
- If I replace `FBLoginButton` with `FBButton` or `FBDeviceButton`, the build success and the app can start.
- If I uncomment and replace `FBSDKLoginManager` with `LoginManager`
  - The editor stop showing error
  - *Jump to definition* point to the file `FBSDKLoginManager.h`
  - When build, the compiler throw error similar to the `FBLoginButton`: `Undefined symbol: _OBJC_CLASS_$_LoginManager`

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LoginManager", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

- If I comment both lines (`FBLoginButton` and `FBButton`), the app build and run successfully.

**Comment by joesus** [comment]
If I understand correctly, you're trying to compile for tvOS but the login button is not available on tvOS. You can implement Facebook Login on tvOS using the class `DeviceLoginManager` - See [Facebook Device Login](https://developers.facebook.com/docs/facebook-login/for-devices).

So the question remains, why are you able to see the symbol for `FBLoginButton` when it's not meant to be used for tvOS. This has to do with a weird situation that we're in due to some decisions made a few years ago.

We need (and want) to support Swift Package Manager (SPM), but SPM does not allow us to conditionally exclude Swift files for compilation by platform. 

So we can try and use availability declarations in Swift. Take this example. If I define a new type in `FBLoginButton.swift` and declare it unavailable:
```
@available(tvOS, unavailable)
public class SomeNewType {
    public init() {}
}
```
If I try to use that in Swift I'll get the error: `'SomeNewType' is unavailable in tvOS`

For `FBSDKLoginButton` we can try to omit this type at the compilation level for ObjC by wrapping it in a macro like:

```
#if !TARGET_OS_TV
 // define the login button here
#endif
```
But if we do that then the Swift extension of the button will not be able to resolve the type `Cannot find type 'FBLoginButton' in scope` despite the extension being marked as unavailable for tvOS.

So we're in a pickle. The only workaround I could find was to declare a dummy interface in `FBSDKLoginButton.h` so that the extension will compile but it leads to the behavior you're seeing where the symbol is visible but not usable.

If you can think of a great way to fix this please open a Pull Request for review. :D
