### ISSUE TITLE
Incompatible library version" when run App crash after Launch. version 9.0

### ISSUE THREAD

**Issue by hardik38737** [facebook/facebook-ios-sdk#1620]
Xcode Version: 12.3
Device : iPhone 12 mini (14.3)

Log :
dyld: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
Referenced from: ~/Library/Developer/CoreSimulator/Devices/28372F6B-6956-46B1-9493-28DE38A88F56/data/Containers/Bundle/Application/4F4A240B-4243-489E-BBCD-B40F40D7E72E/XXX.app/app Name
Reason: Incompatible library version: App name requires version 1.0.0 or later, but FBSDKCoreKit provides version 0.0.0

Below is my pod file :

platform :ios, '9.0'
target 'App name' do
use_frameworks!
pod 'SDWebImage', '>3.8'
pod 'Firebase/Performance'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/DynamicLinks'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
pod 'Google-Mobile-Ads-SDK'
pod 'IronSourceSDK'
pod 'FacebookSDK'
#pod 'FBSDKLoginKit'
#pod 'FBSDKShareKit'
pod 'GoogleMobileAdsMediationMoPub'
pod 'GoogleMobileAdsMediationFacebook'
pod 'IronSourceFacebookAdapter'
pod 'IronSourceTapjoyAdapter'
end

**Comment by hadiidbouk** [comment]
Same problem

**Comment by hadiidbouk** [comment]
Updated Cocoapods to `1.10.1` and now I have this error

```
Multiple commands produce '../Frameworks/FBSDKCoreKit.framework':
1) That command depends on command in Target '..' (project '..'): script phase "[CP] Embed Pods Frameworks"
2) That command depends on command in Target '..' (project '..'): script phase "[CP] Embed Pods Frameworks"
```

**Comment by joesus** [comment]
Hi!

The aggregate pod 'FacebookSDK' vendors XCFrameworks as of v9.0.

The issue that you're seeing is that one of the Pods listed has a dependency on Facebook Audience Network which uses the subspec `FBSDKCoreKit/Basics`. So basically CoreKit is being included in two different ways which are conflicting. This can be fixed by removing `pod 'FacebookSDK'` and adding `pod 'FBSDKCoreKit'`.

I'll update the change log to call this out.
Thanks!
