### ISSUE TITLE
Feature Request: Extend FBSDKAuthenticationToken API

### ISSUE THREAD

**Issue by trofimovps** [facebook/facebook-ios-sdk#1663]
## Checklist

- [+] I've updated to the latest released version of the SDK
- [+] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [+] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [+] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

Improve user experience.

## Expected Results

Add expiration and permissions API to FBSDKAuthenticationToken as it done in FBSDKAccessToken to allow better user experience in cases of token expiration. As for permissions - after restoring FBSDKAuthenticationToken we have no information about permissions it was requested with. 

## Code Samples & Details

Sample API for reference https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKCoreKit/FBSDKCoreKit/FBSDKAccessToken.h

**Comment by ppansy** [comment]
For expiration:
I don't think there is a need to check AuthenticationToken expiration on client side. The reason is Limited Login returns a **static snapshot** of user data at the point of time that login happens, this data would never expire. What's "expiring" for AuthenticationToken is its ability to be used as authentication proof, which SDK already checks for on client side. When pulled server side you can verify the expiration using the [Open ID Standard](https://openid.net/specs/openid-connect-core-1_0.html).

For permissions:
Similar to the point above, I think providing it for AuthenticationToken is misleading, as "permissions" indicates further data access, which is not applicable to Limited Login. As an alternative, you can check `FBSDKProfile.currentProfile` to see what data has been returned.

Open to discuss more on this. Thanks for providing feedback! This calls out that we need some more work on our developer documentation.

**Comment by trofimovps** [comment]
Hello. Thank you for explanation. What we really want to do is to fail fast before sending Authentication token to our server side to create our internal session. 

As I understand the only way to check it is to parse JWT and check expiration the same way server side will do it? Or iOS SDK guaranty we never receive token that could not be used as authentication proof? (That's what really the expiration is in our situation)

**Comment by ppansy** [comment]
The SDK performs all the verification step specified by Open ID standard upon receiving the token. Therefore if you use the token immediately after login, we can guarantee the token supplied by the SDK will be valid. Does that fit your use case?

**Comment by trofimovps** [comment]
I'm interested in case, when we use CurrentAuthenticationToken from FBSDKAuthenticationToken instead of direct call to login.

**Comment by ppansy** [comment]
FBSDKAuthenticationToken.CurrentAuthenticationToken saves the token you get from login. If you use it immediately, we can guarantee that it's valid. But if you use it at an arbitrary point of time, we cannot guarantee it is non-expired.

**Comment by ppansy** [comment]
Will close because I don't see a strong need of these APIs. Lmk if there are additional feedbacks
