### ISSUE TITLE
FacebookSDK/CoreKit is not distributed as a .framework.

### ISSUE THREAD

**Issue by Unknoob** [facebook/facebook-ios-sdk#1703]
## Checklist

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/master/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `12.4`
- Swift Version: `X.X.X` (if issue is Swift related)
- Installation Platform & Version: `[Cocoapods]` version `1.9.0`

## Goals

I'm trying to integrate the FacebookSDK pod in a project using the aggregate pod.

## Expected Results

All the FacebookSDK dependencies downloaded as .frameworks

## Actual Results

While the `FacebookSDK/LoginKit` pod correctly downloads the FBSDKLoginKit.framework, the `FacebookSDK/CoreKit` pod is downloaded as source code instead of a pre-compiled framework.

## Steps to Reproduce

Add 
```
pod 'FacebookSDK', '~> 9.1'
pod 'FacebookSDK/LoginKit', '~> 9.1'
```
to a podfile and run pod install

## Code Samples & Details

The issue is probably in the [FacebookSDK podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/0/c/0/FacebookSDK/9.1.0/FacebookSDK.podspec.json)

As you can see the CoreKit subspec has no `vendored_frameworks` entry.

**Comment by joesus** [comment]
Closing for now since I'm not clear on what the actual issue is here. Is it:

1. that you would like to have exclusively precompiled frameworks? 

If that's the case then I would recommend just using the XCFrameworks attached to the release directly since they're super easy to use. 

2. you want to have (1) but via CocoaPods?

Happy to review any pull requests.

**Comment by K439-co** [comment]
I'll tell you why this happened he has hacked my phone and my fb acct and has all my info for several years. Now he is caught and trying to play it good. He is a criminal.

**Comment by K439-co** [comment]
﻿
﻿Dear Facebook . This person has stolen all my info and has sent you a message from my phone. This is my hacker who had my info and is blocking me from my acct. I want him prosecuted if there is a way. He has made my life miserable when my child was killed in an accident. What kind of a heartless person does that? I'm sure we'll find my photos in his possession.

**Comment by K439-co** [comment]
Facebook, this person used my account to hack and steal all my photos and private info. I found him textingon my phone remotely and I found his GitHub acct with the coding for my devices and my tv. 
He is a thief and need to be reprimanded . He is a criminal for stalking me for 2 yrs. I hope you are going to do something. He also was using my acct as a front for his.
Karen Smith
***@***.***
I'd like my Picts returned

**Comment by K439-co** [comment]
﻿
﻿Dear Facebook, I see you deleted my comments but please let me tell you this.  This person Joe Susnick has been hacking my fb acct and my devices along with my tv. 
I am sending you this email he made originally on my phone. He has put widgets on maps to see my photos and he has tried to set up medical. I found hidden files to access google I didn’t know I had. 
I’m not able to access my fb account I made with the phone number 
4109209949. I tried to do a takeout on that file but it said most of the categories could not be done. I have something but not everything. 
Can you help me? If you think I’m unfairly accusing this person than prove to me I’m wrong. When I tried to access any Karen smith I can’t. 
Just prove me wrong.
I have open ports on my iPhone??????
I found tasks made up in files????
Most of the screen shots I took for proof are missing.

Sent from my iPhone

On Apr 12, 2021, at 9:54 PM, Joe Susnick ***@***.***> wrote:

﻿
Closing for now since I'm not clear on what the actual issue is here. Is it:

that you would like to have exclusively precompiled frameworks?
If that's the case then I would recommend just using the XCFrameworks attached to the release directly since they're super easy to use.

you want to have (1) but via CocoaPods?
Happy to review any pull requests.
