### ISSUE TITLE
App crash during login after SDK upgrade to v9.2.0

### ISSUE THREAD

**Issue by shalinipk** [facebook/facebook-ios-sdk#1733]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/master/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `12.3`
- Swift Version: `5.3.2` (if issue is Swift related)
- Installation Platform & Verison: `Carthage` version `0.37.0`

## Goals

Upgrade to latest Firebase iOS SDK, login using FB successfully

## Expected Results

Upgrade to latest Firebase iOS SDK, login using FB successfully

## Actual Results

app crash while trying to login - validateAppID fails
However, appID & URL schemes are set in Info.plist - has been working fine on previous version v8.0.0

## Steps to Reproduce

upgrade from Firebase iOS SDK v8.0.0 -> v9.2.0, carthage, manual build of sources
(Tried downloading v9.2.0 directly instead of building sources from scratch - seeing same results)

## Code Samples & Details

<img width="1162" alt="Screen Shot 2021-04-30 at 12 05 03 PM" src="https://user-images.githubusercontent.com/8920346/116742493-4dd1db80-a9ac-11eb-9add-530622b3277e.png">

**Comment by 123gid** [comment]
yes very helpful let try

**Comment by 123gid** [comment]
but also can  give details then do it to your end can be much much better for me.

**Comment by 123gid** [comment]
app [online flowery pet bfm stores 472235496666144(bridgefuremarketingonline.com)

**Comment by rosalyntan** [comment]
Seeing a similar crash, but in `isRegisteredURLScheme` instead:
https://github.com/facebook/facebook-ios-sdk/blob/7c3d03d3ab633703e6c69ece97b877978931a8b4/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKInternalUtility.m#L473

`Terminating app due to uncaught exception 'InvalidOperationException', reason: 'fb############### is not registered as a URL scheme. Please add it in your Info.plist'`

I have checked that the URL scheme was correctly set.

No crash in v9.1.0, but seeing the crash in v9.2.0 and v9.3.0.

**Comment by shalinipk** [comment]
Thanks @rosalyntan Let me switch to v9.1.0

**Comment by rosalyntan** [comment]
@shalinipk in case this helps for your case as well -- we believe the reason our app started crashing with v9.2.0 is because we hadn't included the steps in https://developers.facebook.com/docs/facebook-login/ios#delegate when configuring Facebook Login, which resulted in the SDK not properly accessing the values from `Info.plist`. Adding the code from the setup guide into our `AppDelegate` fixed the issue for us.

Not sure why it suddenly stopped working with v9.2.0 when it was working previously, but hope this helps!

**Comment by shalinipk** [comment]
Thank you so much @rosalyntan Turns out we were not calling this piece of code from didFinishLaunchingWithOptions

```
ApplicationDelegate.shared.application(
                    application,
                    didFinishLaunchingWithOptions: options
                )
```

Works now. Thanks a lot for your help!!
