### ISSUE TITLE
Getting a message to update to latest SDK although I'm already at 9.3.0

### ISSUE THREAD

**Issue by ohad-alike** [facebook/facebook-ios-sdk#1754]
At EventManager, I'm getting those two messages:

Update the Facebook SDK for iOS
Your app is out of date. To run your app on iOS 14, update to the latest Facebook SDK for IOS.

Improvements to the Facebook SDK for iOS
We released a newer version of the Facebook SDK for iOS that supports the SKAdNetwork and iOS 14. Update to the latest version for all apps to help enable the delivery and performance of your iOS 14 ad campaigns.

I'm using Swift

**Comment by 123gid** [comment]
Thanks for your concern we are looking forward to resolve the issues. bridge From: ohad-alikeSent: Friday, May 21, 2021 10:14 AMTo: facebook/facebook-ios-sdkCc: SubscribedSubject: [facebook/facebook-ios-sdk] Getting a message to update to latest SDK although I'm already at 9.3.0 (#1754) At EventManager, I'm getting those two messages:Update the Facebook SDK for iOSYour app is out of date. To run your app on iOS 14, update to the latest Facebook SDK for IOS.Improvements to the Facebook SDK for iOSWe released a newer version of the Facebook SDK for iOS that supports the SKAdNetwork and iOS 14. Update to the latest version for all apps to help enable the delivery and performance of your iOS 14 ad campaigns.I'm using Swift—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by joesus** [comment]
Thanks for reaching out to us with this issue! Unfortunately, there is not enough information included here to help debug the issue further. As a result, we are closing this issue at this time. 

Please open a new issue using the Github issue template and be sure to include the requested information to help us debug the issue further OR report this to our designated developer support team here:  https://developers.facebook.com/support/bugs/
