### ISSUE TITLE
<unknown>:0: error: missing required module 'LegacyCoreKit'

### ISSUE THREAD

**Issue by hadiidbouk** [facebook/facebook-ios-sdk#1809]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/master/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

12.5.1

### Swift version

5

### Installation platform & version

SPM

### Package

Core

### Goals

I want to be able to archive my application in order to distribute it to testflight

### Expected results

Successful archive

### Actual results

<unknown>:0: error: missing required module 'LegacyCoreKit'

### Steps to reproduce

it's hard to reproduce in a new project

**Comment by joesus** [comment]
> it's hard to reproduce in a new project

There's not much we can do without a way to reproduce this. If you can make a sample project and compare the various build settings you might be able to find out what the issue is. 

Closing for now since there's no action to take. Please open a new issue with reproduction steps OR report this to our designated developer support team here:  https://developers.facebook.com/support/bugs/ . Thanks!
