### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by yahiaabosaad** [facebook/facebook-ios-sdk#1880]
### Checklist before submitting a feature request

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/master/CODE_OF_CONDUCT.md)

### Goals

https://github.com/facebook/facebook-ios-sdk.git

### Expected results

[Uploading facebook-ios-sdk-master.zip…]()

### Code samples & details

```swift
// INSERT YOUR CODE HERE
var example = "Example code"
```

**Comment by jawwad** [comment]
@yahiaabosaad - It looks like this may have been opened by accident so I'm going to close this out since it doesn't look like a feature request. The goal just has a link to the git repo. If you were expecting to open a feature request go ahead and open a new issue detailing the feature you are requesting.
