### ISSUE TITLE
remove 'FBSDKCoreKit' from Podfile, then my .xcodepro is broken, cannot opened

### ISSUE THREAD

**Issue by Kangqj** [facebook/facebook-ios-sdk#1883]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/master/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

12.1

### Installation platform & version

Cocoapod 1.10.1

### Package

Core

### Goals

pod 'FBSDKCoreKit', '5.2.1'
I remove 'FBSDKCoreKit' from Podfile, and Pod install, then my .xcodepro is broken, cannot opened.
Very strange question，and my project's target is none.

How to solve this problem?

### Expected results

How to solve this problem?

### Actual results

my .xcodepro is broken, cannot opened.

### Steps to reproduce

pod 'FBSDKCoreKit', '5.2.1'
I remove 'FBSDKCoreKit' from Podfile, and Pod install, then my .xcodepro is broken, cannot opened.
Very strange question，and my project's target is none.

How to solve this problem?

### Code samples & details

```swift
pod 'FBSDKCoreKit', '5.2.1'
```

**Comment by jawwad** [comment]
Hi @Kangqj - It sounds like this is an issue that you need some guidance with and not an issue with the SDK. Also there isn't enough information for us to troubleshoot this. You are also using a very old version of the SDK, the current version is 11.2.0.

I would recommend using the latest version of the SDK. You can also try to restore your project file to the latest version on your branch by undoing the changes (for example by running something like `git reset --hard`). If you continue to have issues I'd recommend asking on StackOverflow, since we are unable to prioritize individual issues over ones that actually affect the SDK.
