### ISSUE TITLE
Feature Request: Use static XCFrameworks for cocoapods

### ISSUE THREAD

**Issue by cltnschlosser** [facebook/facebook-ios-sdk#1910]
### Checklist before submitting a feature request

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)

### Goals

Static frameworks are generally seen as better than dynamic frameworks in the iOS community. Version 12 forces cocoapods users to use dynamic frameworks, where before linkage could have been specified with `use_frameworks! :linkage => :static`. If we're forcing one way, I think it should be static.

Alternatively the podspecs could be duplicated into Dynamic and Static versions, or the FacebookSDK aggregate podspec could be updated to use the static XCFrameworks (currently it uses static fat frameworks).

Note: FacebookSDK.podspec has only been published for version 11.2.1, and using it by pointing to git directly results in an error for FacebookSDK/LoginKit because it says LoginKit doesn't support iOS.

### Expected results

`FacebookSDK-Static_XCFrameworks.zip` used in place of `FacebookSDK_Dynamic.xcframework.zip` for cocoapods install.

**Comment by joesus** [comment]
This is a valid request. We used dynamically-linked XCFrameworks in order to preserve the default CocoaPods behavior of using dynamic linking when building from source. 

We'll discuss on the team but ultimately this issue should be resolved at the Podspec level. Currently there is no way that I know of to vend separate XCFrameworks for different linking strategies. Would be happy to learn that there's a way to offer this.

In the meantime, is SPM is an option for your use case? We are distributing statically-linked XCFrameworks that way.

**Comment by joesus** [comment]
> Sounds like I need to look into a cocoapods feature request

I will gladly +1 this request. It would be great for us to be able to support this. 

> Thoughts on fixing up FacebookSDK.podspec and having it use the static XCFrameworks instead of the static frameworks?

I'm very hesitant to go down this road. The distribution ecosystem is already overly fragmented and confusing. I worry that repurposing this pod would

**Comment by cltnschlosser** [comment]
Filed: https://github.com/CocoaPods/CocoaPods/issues/11007 for the feature request, needs to be thought out a bit more, but it would greatly simplify things here.
