### ISSUE TITLE
v12.0.1 requires Xcode 13

### ISSUE THREAD

**Issue by paulb777** [facebook/facebook-ios-sdk#1911]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

12.2

### Facebook iOS SDK version

12.0.1

### Dependency Manager

CocoaPods

### SDK Framework

Core

### Goals

Still builds with Xcode 12

### Expected results

Failed to build

### Actual results

/Users/runner/Library/Developer/Xcode/DerivedData/AuthenticationExample-amzssktckmpoljgwbwizswvdhtiq/Build/Products/Debug-iphonesimulator/FBSDKCoreKit.framework/Modules/FBSDKCoreKit.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:7:8: error: no such module '_Concurrency'
import _Concurrency
       ^
/Users/runner/Library/Developer/Xcode/DerivedData/AuthenticationExample-amzssktckmpoljgwbwizswvdhtiq/Build/Products/Debug-iphonesimulator/FBSDKLoginKit.framework/Modules/FBSDKLoginKit.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:4:8: error: failed to build module 'FBSDKCoreKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'
import FBSDKCoreKit

### Steps to reproduce

Use Xcode 12

This worked fine with 12.0.0

### Code samples & details

```swift
// INSERT YOUR CODE HERE
var example = "Example code"
```

**Comment by jawwad** [comment]
Hi @paulb777,

Thanks for reporting this. The xcframeworks built for the v12.0.1 release were built with Xcode 13 and I guess since they were compiled with Swift 5.5 they won't work with Xcode 12.

I see that you have some PRs in firebase to update to using Xcode 13 which will solve the issue for you. 

I don't think there is an easy way support older version of Xcode while building with Xcode 13 (unless you know of a way, then please let me know). For that reason, unless this is a wider concern, we will only be supporting Xcode 13 going forward. So I'm going to currently mark this as a "wontfix" for now.

I will go ahead and update our changelog, and will pin and leave this issue open for wider visibility.

Thanks for alerting us to this!

**Comment by paulb777** [comment]
@jawwad SGTM. As you pointed out, the issue is resolved for us.

Yep, since Xcode is only forward compatible, we still build binary distributions with Xcode 12.2; anything that requires Xcode 13, we only support in source distributions.

For semantic versioning compliance, technically an Xcode requirement update should be a major version update - and could maybe stretch to a minor version update.

**Comment by jawwad** [comment]
Hi @paulb777,

We discussed this among the team and decided that it would good to maintain support for Xcode 12 for now; so we just released v12.0.2 in which the binaries are built with Xcode 12

Thanks for alerting us to this!
