### ISSUE TITLE
Unable to archive app for distribution using Xcode 12.5.1 and Swift Package Manager

### ISSUE THREAD

**Issue by sasojadrovski** [facebook/facebook-ios-sdk#1917]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

12.5.1

### Facebook iOS SDK version

12.0.2

### Dependency Manager

SPM

### SDK Framework

Core

### Goals

Successfully archive app for distribution using Xcode 12.

### Expected results

Archiving the app should succeed.

### Actual results

A Swift compiler error is reported when archiving the app (Any iOS Device (arm64)) in the FacebookCore module. The error is reported on line `27` in `Exports.swift` — No such module 'FBSDKCoreKit'.

I have tried completely removing the derived data, cleaning the build folder, resetting the package caches, restarting Xcode, etc. Unfortunately, nothing helps. The app builds and runs without any issues on Xcode 12.5.1 with the latest SDK, however, when I try archiving it, it fails immediately.

This issue is not present in `v11.2.1`.

### Steps to reproduce

Use the latest Facebook SDK (`v12.0.2`) and try archiving a project in Xcode 12.5.1.

**Comment by joesus** [comment]
Great catch. We are looking into possible fixes. Confirmed that this cannot be reproduced using Xcode 13. Are you able to upgrade Xcode? 

If that is not an option, you may want to use CocoaPods as a workaround. This bug is specific to SPM and does not exist when using CocoaPods.

Two considerations if you decide to do this:

1) CocoaPods vend the dynamically-linked XCFrameworks as opposed to the statically-linked versions used by SPM.
2) The imports will change from `import Facebook...` to `import FBSDK...`. None of the symbols should need to be changed.

**Comment by jawwad** [comment]
@sasojadrovski,

@joesus has added a fix for this with 3d24f8dc95b9c6bb70bb9ce97a6a2bf71d9b62eb. Could you see if pointing SPM to the `main` branch or to the 3d24f8dc95b9c6bb70bb9ce97a6a2bf71d9b62eb commit fixes the issue for you?

**Comment by jawwad** [comment]
The fix for this is now also available with the release of v12.1.0. Thanks!
