### ISSUE TITLE
[iOS] After updating to v12.1.0 build runs locally but build fails on CircleCI

### ISSUE THREAD

**Issue by Utk2911** [facebook/facebook-ios-sdk#1932]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

13.1

### Facebook iOS SDK version

12.1

### Dependency Manager

CocoaPods

### SDK Framework

Core

### Goals

I have updated the FBSDKCore and FBSDKLogin to the latest v12.1 and the build works fine locally (on my mac) but when building with Circle CI get the following error:
`'FBSDKCoreKit/FBSDKCoreKit.h' file not found`
Can someone help here?

### Expected results

The CircleCi should build the app as building locally.

### Actual results

The CircleCi build fails with the error message. `'FBSDKCoreKit/FBSDKCoreKit.h' file not found`

**Comment by virusnik** [comment]
same problem on Xcode 13.1 after update SPM version from 9.2.0 to 12.1.0
`Circular dependency between modules 'FacebookCore' and 'FBSDKCoreKit'`

**Comment by jawwad** [comment]
HI @Utk2911 - It's weird that you wouldn't have an issue locally but it would fail to build on CircleCI. Is there a difference in how CircleCI is building the project for you vs how you are building it locally? 

@virusnik - You mention that you are having the same problem. Does this mean that you also can build locally but not on CircleCI. It seems like you might have a different issue. Are you able to provide a small example project that reproduces the issue since otherwise it will be difficult to determine why you are encountering the Circular dependency.

**Comment by llKoull** [comment]
Hi!

I have the same problem `Circular dependency between modules 'FacebookCore' and 'FBSDKCoreKit'` But i can't build any of my targets doesn't matter if i'm trying to build them in debug or production mode or even if my target is a real device or a simulator.

Thanks!

**Comment by jawwad** [comment]
@llKoull - It looks like you are having a different issue and not what the title of this issue states, i.e. difficulty in building on CI. Could you open a new issue for the "Circular dependency" issue so that this is tracked separately? We also need to know what package manager you are using (which will be asked in the template once you open a new issue).

**Comment by jawwad** [comment]
Seems like this might be a caching issue on CircleCI. Can you try clearing any cache that CircleCI might be using and try again?

**Comment by jawwad** [comment]
It seems like this is a caching issue with SPM. If you are running into the `Circular dependency` issue locally then running the following will likely fix it: 

```
rm -rf ~/Library/Caches/org.swift.swiftpm
rm -rf ~/Library/Developer/Xcode/DerivedData
```

As for as how to clear the cache on CircleCI, I'm not completely sure but I found the following articles
https://circleci.com/docs/2.0/caching/
https://support.circleci.com/hc/en-us/articles/115015426888-Clear-project-dependency-cache

Please respond to the issue if one of these solutions fixes the issue for you so that others can benefit. Thanks!

**Comment by llKoull** [comment]
Hi @jawwad! 
Yeah! It's working now!!! Thanks for your help! 😉

**Comment by jawwad** [comment]
Hi @llKoull - Thanks for confirming that this worked for you!
