### ISSUE TITLE
Can't share in the messenger

### ISSUE THREAD

**Issue by IgorGalimski** [facebook/facebook-ios-sdk#1981]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

13.1

### Facebook iOS SDK version

11.0

### Dependency Manager

CocoaPods

### SDK Framework

Share

### Goals

Share a link in the messenger

### Expected results

Share dialog is appearing

### Actual results

Not showing share dialog

### Steps to reproduce

1. Use belowed code for share

### Code samples & details

```swift
Use next code

`    FBSDKShareLinkContent *content = [[FBSDKShareLinkContent alloc] init];
    content.contentURL = [NSURL URLWithString:url];

    FBSDKMessageDialog *messageDialog = [[FBSDKMessageDialog alloc] init];
    messageDialog.shareContent = content;
    messageDialog.delegate = self;

    if ([messageDialog canShow]) {
        [messageDialog show];
    }`


But I get false in messageDialog canShow
```

**Comment by joesus** [comment]
You probably checked this already but are you testing on a device that has messenger installed? Also, are you able to reproduce this on the latest release? Thanks!

**Comment by IgorGalimski** [comment]
Yes, the messenger was installed
Yes, i used the latest version

**Comment by samodom** [comment]
@IgorGalimski We are unable to reproduce this issue on our end.

The two checks for `canShow` are:
1. Check the server configuration for the ability to use a native dialog
2. Check that Messenger is installed

Since Messenger is installed, it seems that it must be the configuration associated with your app.  In order to further troubleshoot this issue, can you please open a ticket with our [Support group](https://developers.facebook.com/support) so that you can share your App ID with them and we can see if there is a problem with the configuration?

**Comment by metajet98** [comment]
MessageDialog.show() not working. Still return result == true but cannot open messenger native 

IOS version: 15.1
Messenger app version: 358.0.0.12.127
FBSDKShareKit version: 13.2.0
