### ISSUE TITLE
ApplicationDelegate.shared crashes with `+[FBSDKCoreKitComponents defaultComponents]: unrecognized selector sent to class 0x104a68f48` when using SwiftUI

### ISSUE THREAD

**Issue by trenskow** [facebook/facebook-ios-sdk#2010]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

13.2.1

### Facebook iOS SDK version

12.3.0

### Dependency Manager

SPM

### SDK Framework

Core

### Goals

Trying to inform the shared application delegate, that the application has finished launching.

### Expected results

No crash

### Actual results

Crash

### Code samples & details

```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {

	ApplicationDelegate.shared.application(
		application,
		didFinishLaunchingWithOptions: launchOptions)

}
```

**Comment by georgbachmann** [comment]
Same happens to me. Also SPM and also 12.3.0

**Comment by samodom** [comment]
Thanks for reporting this issue.  We have reproduced it and are preparing a fix.

**Comment by trenskow** [comment]
That sounds great! Thx.

**Comment by trenskow** [comment]
Nice! It's working again. Thanks a lot!

**Comment by samodom** [comment]
@georgbachmann Looks like the newly release v12.3.1 is working for @trenskow -- hopefully it will work for you, too.  Please let us know if it doesn't.

**Comment by nindim** [comment]
Hi,

We have updated to FBSDKCoreKit_Basics 12.3.1, but are still seeing a very similar crash affecting many of our users. We have a different class hash though:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[FBSDKTypeUtility URLValue:]: unrecognized selector sent to class 0x104902c68'

Full crash log here:

[report-2517595323050009999-c76ea300-b322-4da0-b3fa-bff176fa9316.txt](https://github.com/facebook/facebook-ios-sdk/files/7913688/report-2517595323050009999-c76ea300-b322-4da0-b3fa-bff176fa9316.txt)

Can this be looked into as a matter of urgency, please?

Repro steps for crash:

1. Install Facebook app and login
2. Install Sonic Dash from the App Store
2. Boot game
3. Allow ATT tracking
4. Notice crash

Please note, the game then crashes 100% of the time on all subsequent reboots.

Thanks a lot!

**Comment by samodom** [comment]
@nindim This is a different issue and likely means that you have an older version of the AudienceNetwork SDK.  Please make sure you're using v6.9.0 of AudienceNetwork so that you don't have this issue.
