### ISSUE TITLE
IOS: FBSDK not work when facebook app is installed - React Native

### ISSUE THREAD

**Issue by hm-harshit** [facebook/facebook-ios-sdk#2014]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

13.2.1

### Facebook iOS SDK version

12.2.0

### Dependency Manager

Other / I don't know

### SDK Framework

Login

### Goals

Facebook login should redirect properly. 

### Expected results

On React Native IOS With people try to log in with the Facebook app install, It Redirects to a Facebook app again and again on a loop. The problem is only occurring when the user is logged into the Facebook app on a physical device.
Please check the attached POC Video

I am using this plugin https://github.com/thebergamo/react-native-fbsdk-next
 

### Actual results

https://user-images.githubusercontent.com/49211465/150681079-db25706f-3277-4196-aa96-944b4abf3dd6.mp4

**Comment by hm-harshit** [comment]
For more context please check this https://github.com/thebergamo/react-native-fbsdk-next/issues/59

**Comment by jawwad** [comment]
@hm-harshit,

Thanks for reporting this to us but, unfortunately, the react-native-fbsdk-next is something that we won't be able to support. 

If there is something I could do to fix this on the iOS SDK side, I would but the SDK team doesn't have the expertise in working with React Native to see how the SDK is being included or used.

Since we aren't able to provide assistance with this, I'm going to close the issue. However, if you are able to reproduce this issue by using the Facebook iOS SDK alone, then we'd be able to troubleshoot and fix this on our end.

Sorry that I wasn't able to help with this. If you do find a fix please do let us know what fixed it for you. This will also help others in case they search our issues list for this problem.
