### ISSUE TITLE
Failed to archive using Xcode 13.2.1

### ISSUE THREAD

**Issue by hendy-evan** [facebook/facebook-ios-sdk#2062]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

13.2.1

### Facebook iOS SDK version

13.1.0

### Dependency Manager

CocoaPods

### SDK Framework

Core

### Goals

Succesfully archived ipa

### Expected results

Succesfully archived ipa

### Actual results
```
Failed to compile bundle: /var/folders/8y/63_hr4hj31b0tw1gm_l5h32m0000gn/T/FBSDKCoreKit_Basicsepsmbe7q/FBSDKCoreKit_Basics.arm64.xar
Stderr:
>
    /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/ipatool:372:in `run'
    /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/ipatool:2886:in `block in CompileOrStripBitcodeInBundle'
    /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/ipatool:2825:in `each'
    /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/ipatool:2825:in `CompileOrStripBitcodeInBundle'
    /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/ipatool:3112:in `block in ProcessIPA'
    /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/ipatool:3073:in `each'
    /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/ipatool:3073:in `ProcessIPA'
    /Applications/Xcode-13.2.1.app/Contents/Developer/usr/bin/ipatool:4035:in `<main>'}
```
### Steps to reproduce

I tried to archive my project using Travis and Xcode 13.2.1. I already update pods to latest version.
When used Xcode on my local mac (Mac OS 12.3.1 and Xcode 13.3) it's archived successfully.
I'm using development for `export_method`

**Comment by somedev** [comment]
Same here:AdHoc export fails. Debug and Appstore builds are OK.

**Comment by samodom** [comment]
@hendy-evan @somedev Can you try archiving with SDK version 13.2.0?

**Comment by mikehardy** [comment]
I wonder if it is this commit? https://github.com/facebook/facebook-ios-sdk/commit/7c5e9565b94d5e9cab1f617a342f038e204cedf0

Came here from react-native-fbsdk-next via @caiorrsdeg - it's important to note that Xcode 13.2 is the latest version available from a lot of CI providers, as well as lots of dev machines that are admittedly older but *cannot* upgrade to macOS 12 because of Apple planned obsolescence policy. Specifically I've got two otherwise serviceable older machines I use in a build farm that are stuck on macOS 11, and they won't upgrade past Xcode 13.2 unfortunately.

**Comment by samodom** [comment]
@mikehardy I would only expect that to be an issue if RN is building from source -- if then, since the LastUpgradeCheck value *seems* to just be what determines whether you see an upgrade warning while in Xcode.  The reason I proposed using the new version of the SDK is that it was built with Xcode 13.0 and should avoid this particular issue when archiving an app -- with any version of Xcode 13+.

**Comment by mikehardy** [comment]
Hmm - we integrate the cocoapods, which do build from source I believe, but it is unclear to me whether something like last upgrade check value should cause an archive fail. Honestly the Xcode toolchain is a bit mystifying/opaque to me as a mostly-android person so I recognize your hypothesis as likely (if I understand it as "should only affect Xcode warnings, not archive") but it was all I could see in the commit log here so I grasped at the straw.

Hypotheses aside we've definitely got an experimental result of archive failure with Xcode 13.2.1 and facebook-ios-sdk with version 13.1.0 here (https://github.com/thebergamo/react-native-fbsdk-next/blob/a9ed2ccdb873663df26831bdfe5cd652e2028a51/react-native-fbsdk-next.podspec#L16-L30) and we're just not sure what it is, but the user is apparently on the macos-11 AppCenter CI runner so does not currently have access to Xcode 13.3+

@caiorrsdeg - I notice that v13.2.0 of facebook-ios-sdk is released here and we haven't ingested it yet upstream, do you still see the problem if you use https://github.com/ds300/patch-package/ in combination with a local change to the `node_modules/react-native-fbsdk-next/` podspec file that brings in 13.2.0? Perhaps this issue is fixed / not relevant anymore, and we wouldn't want to chase ghosts from an old version

**Comment by samodom** [comment]
> Hypotheses aside we've definitely got an experimental result of archive failure with Xcode 13.2.1 and facebook-ios-sdk with version 13.1.0 here (https://github.com/thebergamo/react-native-fbsdk-next/blob/a9ed2ccdb873663df26831bdfe5cd652e2028a51/react-native-fbsdk-next.podspec#L16-L30) and we're just not sure what it is, but the user is apparently on the macos-11 AppCenter CI runner so does not currently have access to Xcode 13.3+

We've also verified this issue and are pretty sure it's due to the product that later versions of Xcode is producing.  SDK version 13.2.0 should work with any version of Xcode 13 and later.  If you find differently, please let us know.

**Comment by mikehardy** [comment]
Okay - thanks for that. Seems like it's on us to update to 13.2.0 then, I'm on that now and will release it on our side. First need to log an issue with facebook-android-sdk that they have a 13.2.0 but it's not visible on their releases page ;-). Cheers

**Comment by caiorrsdeg** [comment]
> Hmm - we integrate the cocoapods, which do build from source I believe, but it is unclear to me whether something like last upgrade check value should cause an archive fail. Honestly the Xcode toolchain is a bit mystifying/opaque to me as a mostly-android person so I recognize your hypothesis as likely (if I understand it as "should only affect Xcode warnings, not archive") but it was all I could see in the commit log here so I grasped at the straw.
> 
> Hypotheses aside we've definitely got an experimental result of archive failure with Xcode 13.2.1 and facebook-ios-sdk with version 13.1.0 here (https://github.com/thebergamo/react-native-fbsdk-next/blob/a9ed2ccdb873663df26831bdfe5cd652e2028a51/react-native-fbsdk-next.podspec#L16-L30) and we're just not sure what it is, but the user is apparently on the macos-11 AppCenter CI runner so does not currently have access to Xcode 13.3+
> 
> @caiorrsdeg - I notice that v13.2.0 of facebook-ios-sdk is released here and we haven't ingested it yet downstream, do you still see the problem if you use https://github.com/ds300/patch-package/ in combination with a local change to the `node_modules/react-native-fbsdk-next/` podspec file that brings in 13.2.0? Perhaps this issue is fixed / not relevant anymore, and we wouldn't want to chase ghosts from an old version

should I update 13.1.0 to 13.2.0 in these lines?

```
s.subspec 'Core' do |ss|
    ss.dependency     'FBSDKCoreKit', '~> 13.1.0'
    ss.source_files = 'ios/RCTFBSDK/core/*.{h,m}'
  end

  s.subspec 'Login' do |ss|
    ss.dependency     'FBSDKLoginKit', '~> 13.1.0'
    ss.source_files = 'ios/RCTFBSDK/login/*.{h,m}'
  end

  s.subspec 'Share' do |ss|
    ss.dependency     'FBSDKShareKit', '~> 13.1.0'
    ss.dependency     'FBSDKGamingServicesKit', '~> 13.1.0'
    ss.source_files = 'ios/RCTFBSDK/share/*.{h,m}'
  end
```

**Comment by caiorrsdeg** [comment]
@mikehardy updating the package to 8.0.2 worked, thank you!

**Comment by mikehardy** [comment]
Fantastic, thanks in turn to @samodom - cheers all
