### ISSUE TITLE
14.0 version is missing FBSDKLoginManagerLoginResult definition in objc

### ISSUE THREAD

**Issue by martinbonaciugome** [facebook/facebook-ios-sdk#2083]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

13.4.1

### Facebook iOS SDK version

14.0

### Dependency Manager

CocoaPods

### SDK Framework

Login

### Goals

login using objc

### Expected results

existing login code to compile

### Actual results

FBSDKLoginManagerLoginResult definition is missing in the objc version of this version of the sdk

### Steps to reproduce

compile login code in objc

### Code samples & details

```swift
[[FBSDKLoginManager new] logInWithPermissions:permissions fromViewController:System.appDelegate handler:^(FBSDKLoginManagerLoginResult* result, NSError* error)
      {
        if (error)
        {
        }
        else if (result.isCancelled)
        {
        }
      }];

causes:
 Property 'isCancelled' cannot be found in forward class object 'FBSDKLoginManagerLoginResult'
```

**Comment by samodom** [comment]
@martinbonaciugome We are unable to reproduce this with a simple example of our own.  Are you importing the framework in this file or from any imported headers?

**Comment by martinbonaciugome** [comment]
I used to be on 12.2.1 FBSDKCoreKit/FBSDKLoginKit, upgraded my cocoapods to use 14.0, and didn't change any code. my imports are:
`
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBSDKLoginKit/FBSDKLoginKit.h>
`
if you do a search in your sdk on this gihub page, you can see that FBSDKLoginManagerLoginResult is not defined
<img width="990" alt="image" src="https://user-images.githubusercontent.com/6127051/174650092-c2b45d7f-d5f2-4ccc-887c-1cc0574b9ce6.png">

**Comment by samodom** [comment]
@martinbonaciugome The second result in that screenshot is the type in question.  It is accessible from Objective-C with the same name and behavior.

**Comment by martinbonaciugome** [comment]
yes buts it's not accessible through those imports. is there another import i need in objc?

**Comment by martinbonaciugome** [comment]
I can't as I'm using it in a objc++ file. `#import <FBSDKLoginKit/FBSDKLoginKit-Swift.h>` seems to work. This is the compiled framework headers folder that cocoapods generated. It's missing `LoginManagerLoginResult-Swift.h`
<img width="667" alt="image" src="https://user-images.githubusercontent.com/6127051/174851784-15aa6d5b-50c4-48d4-a095-5e2c7f28c2bc.png">

**Comment by martinbonaciugome** [comment]
um ... so you don't want to fix your bug? you can clearly see from the last screen shot that there is no `FBSDKLoginManagerLoginResult.h` file. why there is a single `...-Swift.h` file is questionable. compiling a file with a `.mm` extension (objc++) is not the issue here

**Comment by samodom** [comment]
@martinbonaciugome I closed the ticket because it sounded like importing the generated header had solved your compilation problems.

There is no bug here, however -- the header you're referring to doesn't exist any more and won't exist again because the type has been converted to Swift.  For the time being, it is still accessible from Objective-C since the `FBSDKLoginKit-Swift.h` file is generated with Objective-C declarations for all types written in Swift that are exposed to Objective-C.

Using Swift symbols from C++ is not supported, though there has been [an announcement](https://forums.swift.org/t/swift-and-c-interoperability-workgroup-announcement/54998) about building bidirectional interoperability between the two languages.  The Facebook iOS SDK will continue to be gradually converted to Swift and will ultimately become pure Swift at some point in the future.
