### ISSUE TITLE
Apple Silicon Support?

### ISSUE THREAD

**Issue by yangchen-acc** [facebook/facebook-ios-sdk#2104]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

13.3.1

### Facebook iOS SDK version

14.1.0

### Dependency Manager

SPM

### SDK Framework

Other / I don't know

### Goals

Does anyone know how to make the SDK support M1 Chip?

### Expected results

I should be able to build the project without using Rosetta on M1 Macs

### Actual results

I can't build without using Rosetta

### Steps to reproduce

In the SPM project I can't tweak around the settings to exclude ARM64 architecture or disable build for only active architecture
Xcode is complaining can't find x86_64 simulator when building my project

### Code samples & details

```swift
// INSERT YOUR CODE HERE
var example = "Example code"
```

**Comment by uzunbe** [comment]
Thank you very much my friend, the page has improved now, it is working faster, but notifications are not showing quickly?!, and old notifications appear to me تم الإرسال من Galaxy الخاص بي
-------- الرسالة الأصلية --------من: Yang Chen ***@***.***> التاريخ: ٢٥‏/٨‏/٢٠٢٢  ١٠:١٠ م  (GMT+03:00) إلى: facebook/facebook-ios-sdk ***@***.***> نسخة: Subscribed ***@***.***> الموضوع: [facebook/facebook-ios-sdk] Apple Silicon Support? (Issue #2104) 
Checklist before submitting a bug report

 I've updated to the latest released version of the SDK
 I've searched for existing GitHub issues
 I've looked for existing answers on Stack Overflow, the Facebook Developer Community Forum and the Facebook Developers Group
 I've read the Code of Conduct
 This issue is not security related and can safely be disclosed publicly on GitHub

Xcode version
13.3.1
Facebook iOS SDK version
14.1.0
Dependency Manager
SPM
SDK Framework
Other / I don't know
Goals
Does anyone know how to make the SDK support M1 Chip?
Expected results
I should be able to build the project without using Rosetta on M1 Macs
Actual results
I can't build without using Rosetta
Steps to reproduce
In the SPM project I can't tweak around the settings to exclude ARM64 architecture or disable build for only active architecture
Xcode is complaining can't find x86_64 simulator when building my project
Code samples & details
// INSERT YOUR CODE HERE
var example = "Example code"

**Comment by samodom** [comment]
@yangchen-acc The Swift package isn't buildable -- it only points to binary XCFrameworks.  Those XCFramework artifacts contain slices for running in the simulator on Apple Silicon.
