### ISSUE TITLE
Rejection for ASIdentifierManager

### ISSUE THREAD

**Issue by Samback** [facebook/facebook-ios-sdk#583]
According to the next link 
http://www.idownloadblog.com/2014/02/03/apple-pulling-apps-for-not-showing-ads/
Apple set a new rules to App review and the problem is that FB SDK contains next thing:

FBUitlity.m
- (NSString *)advertiserID {
  NSString *advertiserID = nil;
  Class ASIdentifierManagerClass = [FBDynamicFrameworkLoader loadClass:@"ASIdentifierManager" withFramework:@"AdSupport"];
  if ([ASIdentifierManagerClass class]) {
      ASIdentifierManager *manager = [ASIdentifierManagerClass sharedManager];
      advertiserID = [[manager advertisingIdentifier] UUIDString];
  }
  return advertiserID;
  }

And here is a link to a problem http://stackoverflow.com/questions/21489097/my-app-was-just-rejected-for-using-the-ad-support-framework-which-library-is-re

At the bottom you can find also about rejection of one guy who use FB sdk 3.12

**Comment by gautamMoEngage** [comment]
The app is rejected because you might not be selecting "Yes" for "Does you app use the Adverstising Identifier" . Please click yes for that. Then in the sub options, click the second and the third one. (leave out "serve advertisements in the app").
If you don't want Facebook to track attribution or app installs, follow the link below to remove Ad Support and Advertising Identifier from the Facebook SDK. Hope this helps :) 
http://stackoverflow.com/questions/21574680/app-rejected-because-of-advertisingidentifier-in-facebook-sdk-and-flurry-sdk/21575453#21575453.
