### ISSUE TITLE
FBDialog shouldRotateToOrientation

### ISSUE THREAD

**Issue by jkyin** [facebook/facebook-ios-sdk#692]
I find [this method](https://github.com/facebook/facebook-ios-sdk/blob/master/src/Legacy/FBDialog.m#L148-L157) have a condition judgment `orientation == _orientation`。

Since `return orientation == UIInterfaceOrientationPortrait ...` will judge the orientation and return the bool value, why do we use the later directly.

**Comment by chrisp-fb** [comment]
This is a legacy code path that was written for older versions of the iOS SDK (i.e., before iOS 6). It looks like initially we were using UIDeviceOrientation which was wrong (and fixed in https://github.com/facebook/facebook-ios-sdk/pull/401 ). I agree it looks a little bit redundant now. If you have a specific bug to report, feel free to file details at https://developers.facebook.com/bugs

**Comment by kamaljitchakraborty** [comment]
As per your [UIDevice] is concern you please first check whether all your unsigned initiallize device that had been provided by the manufacturer or if the system is assemble by you itself that support your ISO SDK 6 platform or not.?if it does then from that particular device you download A SUNJAVA database platform into your system from JAVA website which regulate your initialized drivers that is not updated frequently and if your application contain any older version software which frequently BUG your system that also be monitor from that installation.
kCCkamaljitchakraborty

**Comment by jkyin** [comment]
@chrisp-fb Thanks for your explain. :+1:
