### ISSUE TITLE
Access token not used when requesting additional permissions

### ISSUE THREAD

**Issue by nlogax** [facebook/facebook-ios-sdk#693]
When a valid access token is available, requesting additional permissions still requires the user to log in if a session does not already exist in the web browser or Facebook app.
If a different user is logged in, that user will be prompted instead, and you will get a token for the wrong user.
Looks like it would be simple to pass along the token in the browser flow, but I don’t know if the Facebook app supports it in some manner.

**Comment by chrisp-fb** [comment]
>requesting additional permissions still requires the user to log in if...

That's intentional. Having a valid access token is not enough for Facebook to authenticate the user in order to grant additional permissions. The user must be logged in via the browser, the Facebook app, or iOS. Otherwise, you could escalate permissions without the user's consent.

For the second case, the SDK will confirm it's the same user coming back when requesting additional permissions and if it's not, the SDK will classify the request a login failure and close the FBSession.

**Comment by nlogax** [comment]
> Having a valid access token is not enough for Facebook to authenticate the user in order to grant additional permissions.

Could you expand on this? Because it is working for me.

**Comment by chrisp-fb** [comment]
I was referring to your suggestion of passing an existing token to the browser flow and not requiring the browser to already have a user logged in. We want the user to be logged in to explicitly grant the new permissions; otherwise, a stolen token of limited scope could be used to increase its scope automatically.

**Comment by nlogax** [comment]
So is it a bug that it works?

**Comment by chrisp-fb** [comment]
Sorry, I think I misinterpreted your post as a suggestion to not require browser log-in. If the browser is logged in as a different user, then the SDK should fail the login (with reason = com.facebook.sdk:ErrorReauthorizeFailedReasonWrongUser ) so there shouldn't be a bug.

Though you're right the user that was logged into the browser may now have inadvertently granted the permission to the app without realizing - in which case it is a good suggestion to pass along the initial token and do the validation at the authorization dialog instead of just relying on the SDK.

**Comment by nlogax** [comment]
I see. Yeah, to clarify:
I have a token for a user.
I ask for additional permissions in context, like the new guidelines suggest.

One of two bad things happen:

1. A different user is signed in, and permissions are granted for this user instead.
2. No one is signed in and the user must enter username/password, adding lots of friction.

If I pop my own webview and pass the token in the `access_token` param, it works as desired.
But then I am bypassing the SDK and can only use the browser flow.
