### ISSUE TITLE
[Share Link] contentDescription and contentTitle not work with itunes link

### ISSUE THREAD

**Issue by tuanphamanh91** [facebook/facebook-ios-sdk#715]
Sorry for my bad English. I try to change contentDescription and contentTitle when share a itunes.apple.com link but they are not display.
    This is my code:
```
    FBSDKShareLinkContent *content = [[FBSDKShareLinkContent alloc] init];
    content.contentURL = [NSURL URLWithString:@"https://itunes.apple.com/us/app/lucky-goat/id965071944?ls=1&mt=8"];
    content.contentDescription = [NSString stringWithFormat: @"Reached Level %d! I'm so smart :3 :3", bestLevel];
    content.contentTitle = @"Sum Tracks";
    content.imageURL = [NSURL URLWithString:@"https://lh4.googleusercontent.com/-J8pW4_gnoVc/VRmFSnpQ2tI/AAAAAAAAXoE/LwMDskbAuzs/s0/www.Aloxovn.com_icon2048.png"];

    [FBSDKShareDialog showFromViewController:self
                                 withContent:content
                                    delegate:nil];
```
And this is facebook display:
![Image of Yaktocat](https://lh4.googleusercontent.com/-DGpfbkOqi5U/VRmSHijgScI/AAAAAAAAXcY/d9xeJZE5zQc/s0/www.Aloxovn.com_Screen_Shot_2015-03-31_at_1.11.57_AM.png)

Please help me! Many thanks

**Comment by toddkrabach** [comment]
iTunes store links are special cased in their rendering to show the description that is pulled from Apple to ensure that the app is properly represented.  If you would like to supply a custom message along with a link to the app, rather than sharing the iTunes link, share a link to a web page and embed App Links meta tags on that page to refer to the iTunes store link (as well as to deep links within the app and the Android equivalent app links).  See http://applinks.org/ for more information on how to configure the meta tags for App Links.

**Comment by tuanphamanh91** [comment]
thanks for your help :+1:

**Comment by jcope** [comment]
@toddkrabach Thanks for sharing- looking at your profile, either you work for Facebook or just contribute extensively to their frameworks- nice!

Is there a way you could request this information be included in their documentation? If an API has expected behavior that is not documented, then most would either consider it poor documentation, or an incomplete API. I understand you may not be able to include all types of links that FB might override content for- but just a disclaimer that it might replace content values would be nice. 

Cheerio!

**Comment by toddkrabach** [comment]
@jcope, yes, I work at Facebook on the SDKs.

I have updated the reference documentation to include a note that these properties may be overridden for special cased URLs like iTunes links.  It will be updated with our next release.  Thanks for the recommendation.

Thanks,
Todd

**Comment by jcope** [comment]
Thanks @toddkrabach! I ended up updating my SDK to 4.2 to try to resolve the issue, so in the end it is not a complete loss of work, probably for the best that I stop using FBSessions..
