### ISSUE TITLE
Unite tests on SDK 4.0

### ISSUE THREAD

**Issue by marciok** [facebook/facebook-ios-sdk#723]
Hi,
I'm trying to write a unit test to check if my newly created user had been successfully connected to Facebook but I'm stuck on a problem, every time that I try to connect I get redirected to Facebook App or Browser (which is expected for the real application) and never returns to the original app making the test fail. 
On version 3.X there was a class named: [FBTestSession](https://developers.facebook.com/docs/reference/ios/3.0/class/FBTestSession) that got removed on the 4.0 and I couldn't find any sort of replacement.   
:disappointed:

**Comment by chrisp-fb** [comment]
Hi,

 FBTestSession was removed since we there is no more concept of FBSession. Instead, you only need to set the `FBSDKAccessToken currentAccessToken` with a valid access token. There is a `FBSDKTestUsersManager` [0] in our integration test project to make it easier to get access tokens for your test users, but it's not currently public. I'll add a work item to move this to CoreKit and make it public for easier test writing, for our next release. Thanks!

[0] https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKIntegrationTests/FBSDKIntegrationTests/FBSDKTestUsersManager.h
