### ISSUE TITLE
User can't edit the list of permissions

### ISSUE THREAD

**Issue by huyduc** [facebook/facebook-ios-sdk#737]
We've noticed this strange behaviour on our app using the latest SDK (4.0.1). 

At the screen where the app requests for permission, user should be able to select only the subset of permissions via the "Edit the info you provide" button, as below. This is the screenshot from one of our app that's using Facebook iOS SDK 3.21.1

![img_0496](https://cloud.githubusercontent.com/assets/721399/7245513/08947a78-e81f-11e4-8404-9d10daa2f62d.PNG)

The strange behaviour happens on another of our app using Facebook iOS SDK 4.0.1 when that screen doesn't have the button to edit the permission. Even more strange, this only happens on iPhone, not on iPad. Both are running on iOS8 and Facebook App version 28.0

![img_0495](https://cloud.githubusercontent.com/assets/721399/7245498/c39bd1aa-e81e-11e4-8261-990f77510ad4.PNG)

**Comment by chrisp-fb** [comment]
Hi, this is expected behavior as a result of [login migration](https://developers.facebook.com/blog/post/2015/02/26/login-migration/). Apps (like the first screenshot) created after April 30, 2014 were automatically enrolled, while older apps like your second screenshot can still have the old behavior until the April 30th of this year. See that link for more information; or if you feel this is in error please file a report to http://developers.facebook.com/bugs with the app and user IDs that can reproduce the behavior. Thanks!
