### ISSUE TITLE
Missing folders (ImageResources/AudioResources) after pod install

### ISSUE THREAD

**Issue by dalu93** [facebook/facebook-ios-sdk#739]
Hi,

I'm using this label on the `Podfile`:

    pod 'Facebook-iOS-SDK', '< 4.0'

I have to install Facebook-iOS-SDK < 4.0 because I need to publish the app to an iOS6.0 environment.
Trying to do `pod install` again on the project, my workspace is not going to compile because some files are missing (`FBDialogClosePNG.h`, for example). So I checked the repository 3.23.2 tag and I noticed that those folders are on the repo (files aren't **.h/.m**, but **.png**), but they is not downloaded or, I don't know, the bash script written in the prepare_command statement will remove them. Is there a way to solve this issue? Thanks

**Comment by dalu93** [comment]
I know is not cleanest way to solve this issue, but I tried modifying the podspec.json file adding **resources** key as:

    "resources" : [
  	"**/**/*.{png,sh,py,wav}"
    ]
Can you verify this issue and publish something that can resolve it? Thanks

**Comment by chrisp-fb** [comment]
Thanks, it's quite possible changes in cocoapods versions prove to be incompatible with older podspecs unfortunately. For older versions of the FB SDK, I highly suggest using the traditional installation method of downloading and linking the frameworks from https://developers.facebook.com/docs/ios/downloads

**Comment by dalu93** [comment]
Hi Chris,
Thanks for the useful answer. I was thinking since versions older than 4.x are released on Cocoapods, why don't you guarantee functionalities? However, if you can add the string I wrote before on the pod specs, you will solve this problem.

**Comment by chrisp-fb** [comment]
Thanks, to clarify; we can't "guarantee" because Cocoapods make changes between their versions that break; for example if you use 0.35.0 with our FB 3.23.2 podspec, it works fine (I just tried it). So then changed some behavior in 0.36.x that is no longer compatible (I see the same error as you). We'll make a best effort to keep up with Cocoapods changes but it's not feasible for us to go back all the time, especially since we provide a binary version that can always be integrated in lieu of Cocoapods. Also I'm not sure if we can update podspecs for existing versions (generally you're supposed to increase versions for changes).

Your workaround does resolve the initial error, but the consequence of that includes the *.png/*.wav as assets in the resulting program which will increase app size. The prepare_command script is our technique to convert those assets to binary code that has much smaller impact on app size, which we had previously gotten feedback about. That said, thanks for the info; if we get more similar reports we can re-evaluate our options. Thanks.
