### ISSUE TITLE
FBSDKShareDialog not open

### ISSUE THREAD

**Issue by divyaappfusion1** [facebook/facebook-ios-sdk#745]
I am using Facebook Sdk 4.1, https://developers.facebook.com/docs/sharing/ios#Advanced share_dialog I am using FBSDKShareDialog to share Video .It does share Video if user has installed facebook app," Idk whats wrong plz help me in sharing Video using FBSDK 4.1.

NSURL *movieUrl = [info objectForKey:UIImagePickerControllerMediaURL];
FBSDKShareDialog *shareDialog = [[FBSDKShareDialog alloc]init];
NSURL *videoURL=movieUrl;
FBSDKShareVideo *video = [[FBSDKShareVideo alloc] init];
video.videoURL = videoURL;
FBSDKShareVideoContent *content = [[FBSDKShareVideoContent alloc] init];
content.video = video;

shareDialog.shareContent = content;
shareDialog.delegate=self;
[shareDialog show];
i am getting response for console

error:Error Domain=com.facebook.sdk.share Code=2 "The operation couldn’t be completed. (com.facebook.sdk.share error 2.)" UserInfo=0x19784210 {com.facebook.sdk:FBSDKErrorArgumentValueKey=, com.facebook.sdk:FBSDKErrorArgumentNameKey=shareContent, com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Share content must be FBSDKShareLinkContent or FBSDKSharePhotoContent in order to share with the share sheet.}

**Comment by chrisp-fb** [comment]
This is by design. For now sharing video content requires the FB App if you're using the FBSDKShareDialog (the alternative is to ask the user to login and grant permissions and construct a manual FBSDKGraphRequest to post a video). You can call `shareDialog canShow` to determine beforehand if the share will work, If you usethe FBSDKShareButton, the button will automatically disable itself when it cannot share.
