### ISSUE TITLE
Umbrella header "FBSDKCoreKit.h" not found in iOS8.3, cocoapods, xcode 6.3

### ISSUE THREAD

**Issue by raulooo** [facebook/facebook-ios-sdk#747]
This is my cocoapods

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!

pod 'Alamofire'
pod "SwiftyJSON", ">= 2.2"

pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

**Comment by chrisp-fb** [comment]
which Cocoapods version are you on? (run `pod --version`). I'm using 0.37.0 and am not able to reproduce any errors when trying your podfile with a Swift app. Can you provide more information?

**Comment by raulooo** [comment]
I have pod 0.37.0

Apple Swift version 1.2 (swiftlang-602.0.49.6 clang-602.0.49)
Target: x86_64-apple-darwin14.3.0

XCode Version 6.3.1 (6D1002)

Is there anything in the build settings I should look at?

**Comment by chrisp-fb** [comment]
Maybe, did you make any explicit changes to the build settings?

Can you include the entire error message and if Xcode tells you the source of the error?

**Comment by raulooo** [comment]
I have this 

![screen shot 2015-05-04 at 6 24 19 pm](https://cloud.githubusercontent.com/assets/1880142/7464720/d777d0d6-f28a-11e4-9c83-15f4817abe92.png)


This is the error in module.modulemap
![screen shot 2015-05-04 at 6 18 46 pm](https://cloud.githubusercontent.com/assets/1880142/7464610/0e148de2-f28a-11e4-9f8c-1269886c4be1.png)

I removed bridging file and removed the reference.

**Comment by chrisp-fb** [comment]
That's odd; the default module map generated by Cocoapods should reference "Pods-FBSDKCoreKit-umbrella.h". We didn't specify a custom module map for Cocoapods (since they only just supported that). Here's what I see in my project.
![screen shot 2015-05-05 at 11 53 29 am](https://cloud.githubusercontent.com/assets/2467488/7480440/60729f82-f31d-11e4-88f6-1527793590ff.png)

Did you make any other customizations? You could delete the Pods dir and workspace and attempt another pod install (and verify you're getting 4.1 of the FBSDKs)

**Comment by chrisp-fb** [comment]
Let me know if you get more info.

**Comment by raulooo** [comment]
Should this be the correct way to import FBSDKCoreKit ? 

I'm getting the umbrella error because of this. Should I use a bridging header?

![screen shot 2015-05-22 at 11 43 01 pm](https://cloud.githubusercontent.com/assets/1880142/7782439/44599a7c-00dc-11e5-810f-361b44bd6bb8.png)
