### ISSUE TITLE
FBSDkAppInviteContent

### ISSUE THREAD

**Issue by SebastianBO** [facebook/facebook-ios-sdk#749]
FBSDKAppInviteContent *content =[[FBSDKAppInviteContent alloc] initWithAppLinkURL:[NSURL URLWithString:@"https://www.mydomain.com/myapplink"]];

The error: no visible @interface for 'FBSDKAppInviteContent' declares the selector 'initWithAppLinkURL:'

Version: Facebook SDK 4.0.1.

**Comment by chrisp-fb** [comment]
That initializer was [removed in 4.1](https://developers.facebook.com/docs/ios/upgrading-4.x) so that FBSDKAppInviteContent is more consistent with other model types. Use the standard parameterless initializer and set the property instead. 

Thanks for the report, I've now updated the code snippet in the tutorial https://developers.intern.facebook.com/docs/app-invites/ios

**Comment by SebastianBO** [comment]
And the updated code works for you? Crashes for me still...

FBSDKAppInviteContent *content =[[FBSDKAppInviteContent alloc] init];
    content.appLinkURL = [NSURL URLWithString:@"https://www.mydomain.com/myapplink"]; <- crashes with 'unrecognized selector sent to instance 0x17042fc60'

**Comment by chrisp-fb** [comment]
Yes, the updated code works. Maybe you are linking to different versions of the SDK, I would check your project's framework search paths and verify.
