### ISSUE TITLE
Sharing an access token with app extensions?

### ISSUE THREAD

**Issue by kevboh** [facebook/facebook-ios-sdk#753]
I'm using `FBSDKLoginButton` to allow Facebook login in my app. I also have a share extension. However, `FBSDKAccessToken.currentAccessToken()` is nil in my share extension even after I log in in my app.

Can I control where the access token is stored such that I can move it to my shared app group, keychain, or user defaults, and access it in my share extension?

**Comment by sebbean** [comment]
you can get the string and store it in a communal NSUserDefaults?

**Comment by kevboh** [comment]
I can, I just don't know if there's a blessed way to share tokens baked into the SDK. The caching classes are private, so assuming not.

**Comment by chrisp-fb** [comment]
You cannot control where the token is stored, but you can observe when it changes (`FBSDKAccessTokenDidChangeNotification`) and then store it yourself somewhere accessible by your extension. You should treat tokens like other user credentials and not put them in user defaults. You could create a shared keychain group between your app and extension to copy the token to.

Note I'm not entirely sure how compatible the SDK is with extension programming at this time since we may use some APIs that are unavailable to app extensions (e.g., `UIApplication sharedApplication`). We're looking into how we may support this better (workaround for now would be to fork/clone and remove the unavailable API calls) but feedback or suggestions would be welcome.
